import React from 'react';
import Button from '../components/Button';
import { Printer, CheckCircle, XCircle, Shield } from 'lucide-react';

const AuditReport = () => {
  const data = {
    ua: navigator.userAgent,
    res: `${window.screen.width}x${window.screen.height}`,
    cores: navigator.hardwareConcurrency || 'N/A',
    mem: navigator.deviceMemory || 'N/A',
    cookies: navigator.cookieEnabled ? 'Enabled' : 'Disabled',
    online: navigator.onLine ? 'Yes' : 'No',
    https: window.location.protocol === 'https:' ? 'Yes' : 'No',
    time: new Date().toString()
  };

  const print = () => window.print();

  return (
    <div className="pt-28 min-h-screen max-w-4xl mx-auto p-8">
      <div className="flex justify-between items-center mb-8 no-print">
          <h1 className="text-4xl font-black uppercase">System Audit</h1>
          <Button onClick={print} variant="secondary"><Printer className="mr-2"/> Print Report</Button>
      </div>

      <div className="bg-white border-4 border-black p-12 print:border-2 print:p-0 print:shadow-none neo-shadow" id="audit-area">
          <div className="border-b-4 border-black pb-6 mb-8 flex justify-between items-center">
              <div>
                  <h2 className="text-3xl font-black uppercase">Sentinel Secure</h2>
                  <p className="font-mono text-gray-600">Forensic Snapshot v2.4</p>
              </div>
              <Shield size={64} className="text-black"/>
          </div>

          <div className="grid grid-cols-2 gap-8 mb-8">
              <div>
                  <h3 className="font-bold uppercase text-gray-500 mb-2">Device Identity</h3>
                  <p className="font-mono bg-gray-100 p-2 border border-gray-300 text-xs break-all">{data.ua}</p>
              </div>
              <div>
                  <h3 className="font-bold uppercase text-gray-500 mb-2">Timestamp</h3>
                  <p className="font-mono font-bold">{data.time}</p>
              </div>
          </div>

          <table className="w-full border-2 border-black text-left mb-8">
              <thead className="bg-black text-white uppercase">
                  <tr>
                      <th className="p-4 border-r border-gray-600">Metric</th>
                      <th className="p-4">Status</th>
                      <th className="p-4 text-right">Verdict</th>
                  </tr>
              </thead>
              <tbody className="font-mono">
                  <tr className="border-b border-black">
                      <td className="p-4 border-r border-black font-bold">HTTPS Connection</td>
                      <td className="p-4">{data.https}</td>
                      <td className="p-4 text-right">{data.https === 'Yes' ? <CheckCircle className="inline text-green-600"/> : <XCircle className="inline text-red-600"/>}</td>
                  </tr>
                  <tr className="border-b border-black">
                      <td className="p-4 border-r border-black font-bold">CPU Cores Available</td>
                      <td className="p-4">{data.cores}</td>
                      <td className="p-4 text-right"><CheckCircle className="inline text-green-600"/></td>
                  </tr>
                  <tr className="border-b border-black">
                      <td className="p-4 border-r border-black font-bold">Cookies Enabled</td>
                      <td className="p-4">{data.cookies}</td>
                      <td className="p-4 text-right"><CheckCircle className="inline text-green-600"/></td>
                  </tr>
                  <tr className="border-b border-black">
                      <td className="p-4 border-r border-black font-bold">Screen Fingerprint</td>
                      <td className="p-4">{data.res}</td>
                      <td className="p-4 text-right text-yellow-600 font-bold">TRACKABLE</td>
                  </tr>
              </tbody>
          </table>

          <div className="bg-gray-50 p-6 border-2 border-black text-center">
              <p className="uppercase font-black text-xl mb-2">End of Report</p>
              <p className="text-xs">Generated by Sentinel Secure Client-Side Engine.</p>
          </div>
      </div>
      
      {/* Print Styles */}
      <style>{`
        @media print {
            .no-print { display: none; }
            body { background: white; }
            .neo-shadow { box-shadow: none !important; }
        }
      `}</style>
    </div>
  );
};
export default AuditReport;